import{parseMusicXml}from"./src/musicxml.js";import{makeChangeset,saveSong,snapshotStudio}from"./src/studio-model.js";
let lib=structuredClone(typeof songs==="undefined"?[]:songs),id=null,history=[],changes=[];const q=x=>document.getElementById(x),fields=["title","artist","key","audio","sheet","content"],download=(name,text)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"application/json"}));a.download=name;a.click()};
function draw(){const x=q("search").value.toLowerCase();q("list").replaceChildren();lib.filter(s=>(s.title+s.artist+s.content).toLowerCase().includes(x)).sort((a,b)=>a.title.localeCompare(b,"vi")).forEach(s=>{const b=document.createElement("button");b.className="song"+(s.id===id?" active":"");b.textContent=s.title+" · "+(s.artist||"Chưa rõ");b.onclick=()=>load(s);q("list").append(b)})}
function load(s){id=s.id;fields.forEach(k=>q(k).value=s[k]||"");q("sourceUrl").value=s.sourceUrl||"";q("heading").textContent="Chỉnh sửa: "+s.title;draw();check()}
function blank(){id=null;fields.forEach(k=>q(k).value="");q("sourceUrl").value="";q("heading").textContent="Thêm bài hát";draw();check()}
function check(){const t=q("content").value;q("preview").textContent=t;q("valid").textContent=!q("title").value.trim()||!t.trim()?"Cần tên bài và nội dung.":"Sẵn sàng lưu."}
function save(){if(!q("title").value.trim()||!q("content").value.trim())return check();history.push(snapshotStudio(lib,changes,id));const editable=Object.fromEntries(fields.map(k=>[k,q(k).value.trim()]));editable.key||="C";const result=saveSong(lib,id,editable,{sourceUrl:q("sourceUrl").value});lib=result.library;changes.push({op:result.op,song:result.song});load(result.song);q("status").textContent="Đã lưu tạm."}
function remove(){if(!id)return;history.push(snapshotStudio(lib,changes,id));changes.push({op:"delete",songId:id});lib=lib.filter(s=>s.id!==id);blank()}
q("xml").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const s=parseMusicXml(r.result,f.name);blank();Object.entries(s).forEach(([k,v])=>q(k).value=v);check()}catch(error){q("status").textContent=error.message}};r.readAsText(f)};
q("importPaste").onclick=()=>{q("content").value=q("hacPaste").value.trim();check()};q("search").oninput=draw;fields.forEach(k=>q(k).oninput=check);q("new").onclick=blank;q("save").onclick=save;q("remove").onclick=remove;q("undo").onclick=()=>{if(history.length){const state=history.pop();lib=state.library;changes=state.changes;const selected=lib.find(s=>String(s.id)===String(state.selectedId));selected?load(selected):blank();q("status").textContent="Đã hoàn tác."}};q("out").onclick=()=>download("songs.js","const songs = "+JSON.stringify(lib,null,2)+";\n");q("exportChanges").onclick=()=>{try{const set=makeChangeset(q("editorName").value,changes,globalThis.HOPAM_DATA_REVISION);download("changeset-"+Date.now()+".json",JSON.stringify(set,null,2));q("collabStatus").textContent="Đã xuất changeset."}catch(e){q("collabStatus").textContent=e.message}};draw();blank();q("status").textContent=`Đã nạp ${lib.length} bài · revision ${globalThis.HOPAM_DATA_REVISION?.slice(0,7)||"không rõ"}`;
